Revert "Release beauharnois-27 (#989)"
This reverts commit cbba4764dab2ecf1074de14dd08261c7e759209d.

diff --git a/gldcore/scripts/gridlabd-version b/gldcore/scripts/gridlabd-version
--- a/gldcore/scripts/gridlabd-version
+++ b/gldcore/scripts/gridlabd-version
@@ -1,14 +1,11 @@
 #!/bin/bash
 
 EXE="$(basename $0)"
-BIN=${0/-version/.bin}
 
 function error()
 {
-	RC=$1
-	shift 1
-	echo "ERROR [$EXE] $*" > /dev/stderr
-	exit $RC
+	echo "$EXE: ERROR $*" > /dev/stderr
+	exit $1
 }
 
 case "$1" in
@@ -30,44 +27,46 @@ function version-help()
 		Syntax: gridlabd version [--dryrun] <command> <options...>
 		Commands:
 		  help                    get this list of commands
-		  check [-v|-q|-w]        check for a newer version
-		    -v                      enable verbose output
-		    -q                      disable all output
-		    -w                      only output warnings and errors and log check result
+		  check [-v|-q]           check for a newer version
 		  list [<pattern>]        get a list of available versions
 		  show                    show the current active version
 		  set [<pattern>]         set the active version
 		  source                  open source code of the active version
 		  delete [-a|<pattern>]   delete versions
-		    -a                      delete all version except current one
 	END
 }
 
 function version-check()
 {
-	version=$(${BIN} --version)
-	branch=$(${BIN} --version=git-branch)
-	remote=$( (curl -sL "https://raw.githubusercontent.com/slacgismo/gridlabd/$branch/gldcore/version.h" | grep '#define REV_' | cut -f3 -d' ' | tr '\n' . | cut -f-3 -d.) || echo "none" )
-	if [ "$remote" == "none" -o -z "$remote" ]; then
-		[ "$1" != "-q" ] && error 2 "$version ($branch) remote not found"
-		exit 2
+	local=$(gridlabd --version=commit)
+	branch=$(gridlabd --version=branch)
+	origin=$(git remote)
+	remote=$(git rev-parse $origin/$branch 2>/dev/null)
+	if [ "$remote" == "$origin/$branch" ]; then
+		remote=none
 	fi
-	[ "$1" == "-v" ] && echo "REMOTE/$branch $remote"
-	${BIN} --version="-ge $remote" 2>/dev/null || ( ( [ "$1" != "-q" ] && error 1 "$version ($branch) is outdated" ) ; exit 1 )
-	[ "$1" != "-q" -a "$1" != "-w" ] && echo "$version ($branch) is ok"
-	[ "$1" == "-w" ] && ( curl -sL "http://version.gridlabd.us/index.html?v=${version}&b=${branch}" >/dev/null & )
-	exit 0
+	if [ "$1" == "-v" ]; then
+		echo "REMOTE $remote"
+		echo "LOCAL $local"
+	fi
+	if [ "$remote" == "none" ]; then
+		[ -z "$1" ] && error 2 "$(gridlabd --version) remote '$origin/$branch' not found"
+	elif [ "$local" != "$remote" ]; then
+		[ -z "$1" ] && error 1 "$(gridlabd --version) is outdated"
+	else
+		[ -z "$1" ] && error 0 "$(gridlabd --version) is ok"
+	fi
 }
 
 function version-source()
 {
-	open $(${BIN} git commit HEAD html_url | sed -e 's:/commit/:/tree/:')
+	open $(gridlabd git commit HEAD html_url | sed -e 's:/commit/:/tree/:')
 }
 
 function version-save()
 {
 	if [ -f /usr/local/bin/gridlabd -a ! -L /usr/local/bin/gridlabd ]; then
-		SAVED="$(${BIN} --version | cut -f2 -d' ')-saved_$(date '+%Y%m%d')"
+		SAVED="$(/usr/local/bin/gridlabd --version | cut -f2 -d' ')-saved_$(date '+%Y%m%d')"
 		N=0
 		TRY="$SAVED"
 		while [ -d /usr/local/opt/gridlabd/$TRY ]; do
@@ -95,7 +94,7 @@ function version-set()
 		L=$(cd /usr/local/opt/gridlabd ; ls -1d *$1* | grep -v current)
 	fi
 	if [ -z "$L" ]; then
-		L="$(${BIN} --version=name | sed -e 's/^gridlabd-//')"
+		L="$(${0/$EXE/gridlabd} --version=name | sed -e 's/^gridlabd-//')"
 	elif [ "$(echo $L | wc -w)" -gt 1 ]; then
 		error 2 "ambiguous version"
 	fi
