Update gridlabd-template

diff --git a/gldcore/scripts/gridlabd-template b/gldcore/scripts/gridlabd-template
--- a/gldcore/scripts/gridlabd-template
+++ b/gldcore/scripts/gridlabd-template
@@ -108,19 +108,19 @@ INDEX=$CACHEDIR/$COMMIT_ID
 
 function fetch_index()
 {
-	if [ ! -d $DATADIR ]; then
-		mkdir -p $DATADIR || error 1 "unable to create $DATADIR"
+	if [ ! -d "$DATADIR" ]; then
+		mkdir -p "$DATADIR" || error 1 "unable to create $DATADIR"
 	fi
-	if [ ! -d $CACHEDIR ]; then
-		mkdir -p $CACHEDIR || error 1 "unable to create $CACHEDIR"
+	if [ ! -d "$CACHEDIR" ]; then
+		mkdir -p "$CACHEDIR" || error 1 "unable to create $CACHEDIR"
 	fi
-	if [ ! -f $INDEX ]; then
+	if [ ! -f "$INDEX" ]; then
 		echo -n "Downloading ${GITBRANCH} index of $ORGANIZATION template archive from ${GITPROJ}... "
 #		svn $SVNLSOPTIONS ls $GITPROJ/branches/$GITBRANCH/$ORGANIZATION | grep '.*$' > $INDEX || rm -f $INDEX
-		curl -s $GITHUBUSERCONTENT/$GITPROJ/branches/$GITBRANCH/$ORGANIZATION/.index >$INDEX
-		echo $(wc -l $INDEX | sed -e 's/ \+/ /g;s/^ //' | cut -f1 -d' ') "template files found"
+		curl -sL "$GITHUBUSERCONTENT/$GITPROJ/branches/$GITBRANCH/$ORGANIZATION/.index" >"$INDEX"
+		echo $(wc -l "$INDEX" | sed -e 's/ \+/ /g;s/^ //' | cut -f1 -d' ') "template files found"
 	fi
-	if [ ! -f $INDEX ]; then
+	if [ ! -f "$INDEX" ]; then
 		error 1 "unable to fetch index"
 	fi
 }
@@ -162,8 +162,8 @@ function help()
 
 function clean()
 {
-	rm -rf $CACHEDIR 
-	if [ -d $CACHEDIR ]; then
+	rm -rf "$CACHEDIR" 
+	if [ -d "$CACHEDIR" ]; then
 		error 1 "unable to delete $CACHEDIR"
 	fi
 	fetch_index
@@ -208,7 +208,7 @@ function list()
 {
 	fetch_index
 	for f in $(export FORMAT=default; index $1); do
-		if [ -f $DATADIR/$f ]; then
+		if [ -f "$DATADIR/$f" ]; then
 			echo $f
 		fi
 	done
@@ -218,12 +218,14 @@ function get()
 {
 	fetch_index
 	for f in $(export FORMAT=default; index $1); do
-		if [ ! -f $DATADIR/$f ]; then
+		if [ ! -f "$DATADIR/$f" ]; then
 			echo -n "Downloading $f... "
-			(curl -s $GITFILE/$ORGANIZATION/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (rm -f /tmp/$$; error 1 "unable to download $f")
+			(curl -sL "$GITFILE/$ORGANIZATION/$f" > "/tmp/$$" && mv "/tmp/$$" "$DATADIR/$f" && echo "done") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
+			[ "${f##*.}" == "zip" ] && unzip -qq -o "$f" -d "$DATADIR"
 		else
 			echo -n "Refreshing $f... "
-			(curl -s $GITFILE/$ORGANIZATION/$f -z $DATADIR/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (rm -f /tmp/$$; error 1 "unable to refresh $f")
+			(curl -sL "$GITFILE/$ORGANIZATION/$f" -z "$DATADIR/$f" > "/tmp/$$" && mv "/tmp/$$" "$DATADIR/$f" && echo "done") || (rm -f "/tmp/$$"; error 1 "unable to refresh $f")
+			[ "${f##*.}" == "zip" ] && unzip -qq -o "$f" -d "$DATADIR"
 		fi
 	done
 }
@@ -236,7 +238,7 @@ function info()
 	if [ "$FORMAT" == "json" ]; then
 		echo "["
 		for f in $(export FORMAT=default; index $1); do
-			if [ -f $DATADIR/$f ]; then
+			if [ -f "$DATADIR/$f" ]; then
 				if [ "$first" == "yes" ]; then
 					first="no"
 				else
@@ -245,7 +247,7 @@ function info()
 				echo "	{"
 				echo "		\"datadir\" : \"$DATADIR/$f\","
 				for KEY in ${KEYWORDS//,/ }; do
-					VALUE=`grep "^#define TEMPLATE_$KEY=" $DATADIR/$f | cut -f2 -d=`
+					VALUE=`grep "^#define TEMPLATE_$KEY=" "$DATADIR/$f" | cut -f2 -d=`
 					echo "		\"$KEY\" : ${VALUE:-None},"
 				done
 				echo "		\"organization\" : \"$ORGANIZATION\""
@@ -260,14 +262,14 @@ function info()
 		echo $(index $1)
 	else
 		for f in $(export FORMAT=default; index $1); do
-			if [ -f $DATADIR/$f ]; then
+			if [ -f "$DATADIR/$f" ]; then
 				if [ "$first" == "yes" ]; then
 					echo "Filepath,Organization,$KEYWORDS"
 					first="no"
 				fi
 				echo -n "$DATADIR/$f,$ORGANIZATION"
 				for KEY in ${KEYWORDS//,/ }; do
-					VALUE=`grep "^#define TEMPLATE_$KEY=" $DATADIR/$f | cut -f2 -d=`
+					VALUE=`grep "^#define TEMPLATE_$KEY=" "$DATADIR/$f" | cut -f2 -d=`
 					echo -n ",${VALUE:-\"\"}"
 				done
 				echo ""
@@ -282,36 +284,35 @@ function copy()
 	if [ $# -eq 0 ]; then
 		error 1 "missing template name"
 	fi
-	FROM=$DATADIR/$1
-	if [ ! -r $FROM ]; then
+	FROM="$DATADIR/$1"
+	if [ ! -r "$FROM" ]; then
 		error 2 "$FROM not found"
 	fi
 	TO=$1
 	if [ $# -gt 1 ]; then
 		TO=$2
 	fi
-	if [ -f $TO ]; then
+	if [ -f "$TO" ]; then
 		error 3 "$TO exists"
 	fi
 	if [ $# -eq 1 ]; then
 		cp $FROM $TO || exit 4
 		exit 0
 	fi
-	EXT=${TO##*.}
-	# convert automatically (TODO such that only objects are saved)
-	TMP=/tmp/tmp-$$
-	sed -e '1,$s/^#define TEMPLATE_Module="\(.*\)"/module \1;/' < $FROM > $TMP.glm || exit 5
-	gridlabd -D filesave_options=OBJECTS -D glm_save_options=MINIMAL -C $TMP.glm -o $TMP.$EXT || exit 6
-	cat $TMP.$EXT > $TO || exit 7
-	rm -f $TMP.*
+	EXT="${TO##*.}"
+	TMP="/tmp/tmp-$$"
+	sed -e '1,$s/^#define TEMPLATE_Module="\(.*\)"/module \1;/' < "$FROM" > "$TMP.glm" || exit 5
+	gridlabd -D filesave_options=OBJECTS -D glm_save_options=MINIMAL -C "$TMP.glm" -o "$TMP.$EXT" || exit 6
+	cat "$TMP.$EXT" > "$TO" || exit 7
+	rm -f "$TMP.*"
 }
 
 function delete()
 {
 	fetch_index
 	for f in $(export FORMAT=default; index $1); do
-		if [ -f $DATADIR/$f ]; then
-			rm -f $DATADIR/$f || error 1 "unable to delete $f"
+		if [ -f "$DATADIR/$f" ]; then
+			rm -f "$DATADIR/$f" || error 1 "unable to delete $f"
 		fi
 	done
 
@@ -322,13 +323,13 @@ function open()
 	if [ $# -eq 0 ]; then
 		error 1 "missing local template name"
 	fi
-	LIBDIR=$1
-	if [ -d $LIBDIR -a -d $LIBDIR/.git ]; then
-		cd $LIBDIR
+	LIBDIR="$1"
+	if [ -d "$LIBDIR" -a -d "$LIBDIR/.git" ]; then
+		cd "$LIBDIR"
 		git pull -q
 	else
-		git clone -q "$GITPROJ" $LIBDIR
-		cd $LIBDIR
+		git clone -q "$GITPROJ" "$LIBDIR"
+		cd "$LIBDIR"
 	fi
 	if [ ! -d .git ]; then
 		error 3 "$LIBDIR is not a valid git repository (missing $LIDIR/.git)"
@@ -337,7 +338,7 @@ function open()
 	if [ -z "$EMAIL" ]; then
 		error 3 "user.email not set for repository $LIBDIR"
 	fi
-	SESSION=$USER/$(date '+%y%m%d/%H%M%S')
+	SESSION="$USER/$(date '+%y%m%d/%H%M%S')"
 	git checkout -q -b $SESSION
 }
 
@@ -346,8 +347,8 @@ function session()
 	if [ $# -eq 0 ]; then
 		error 1 "missing local template name"
 	fi
-	LIBDIR=$1
-	if [ ! -d $LIBDIR -o ! -d $LIBDIR/.git ]; then
+	LIBDIR="$1"
+	if [ ! -d "$LIBDIR" -o ! -d "$LIBDIR/.git" ]; then
 		error 2 "$LIBDIR is not a valid local template"
 	fi
 	if [ $# -eq 1 ]; then
@@ -362,11 +363,11 @@ function save()
 	if [ $# -eq 0 ]; then
 		error 1 "missing local template name"
 	fi
-	LIBDIR=$1
-	if [ ! -d $LIBDIR/.git ]; then
+	LIBDIR="$1"
+	if [ ! -d "$LIBDIR/.git" ]; then
 		error 2 "$LIBDIR is not a valid git repository (missing $LIDIR/.git)"
 	fi
-	cd $LIBDIR
+	cd "$LIBDIR"
 	if [ $# -eq 1 ]; then
 		$MESSAGE="Save by $USER on $DATE"
 	else
@@ -375,8 +376,8 @@ function save()
 	git commit -a -m "$MESSAGE"
 	git push
 	SESSION=$(git branch | grep '^*' | cut -f2 -d' ')
-	file=$GITPROJ/compare/master...$SESSION
-	eval $OPENURLCMD
+	file="$GITPROJ/compare/master...$SESSION"
+	eval "$OPENURLCMD"
 }
 
 function add()
@@ -384,16 +385,16 @@ function add()
 	if [ $# -eq 0 ]; then
 		error 1 "missing local template name"
 	fi
-	LIBDIR=$1
+	LIBDIR="$1"
 	if [ $# -eq 1 ]; then
 		error 2 "missing file name"
 	fi
-	cd $LIBDIR
-	git add -q $2
+	cd "$LIBDIR"
+	git add -q "$2"
 }
 
 if [ "$1" == "-f" -o "$1" == "--format" ]; then
-	FORMAT=$2
+	FORMAT="$2"
 	shift 2
 fi
 
