Fix validation error for openfido

diff --git a/gldcore/scripts/gridlabd-openfido b/gldcore/scripts/gridlabd-openfido
--- a/gldcore/scripts/gridlabd-openfido
+++ b/gldcore/scripts/gridlabd-openfido
@@ -1,15 +1,11 @@
 #!/bin/bash
 if [ ! -x /usr/local/bin/openfido ]; then
-	if [ "$1" == "-h" -o "$1" == "--help" -o "$1" == "help" ]; then
-		echo "Syntax: gridlabd-openfido [-h|--help|help|install-cli]"
-		exit 0
-	elif [ "$1" == "install-cli" ]; then
-		curl -sL https://raw.githubusercontent.com/openfido/cli/main/install.sh | bash
-		exit 0
-	else
-	    echo "ERROR [openfido]: CLI is not installed" > /dev/stderr
-    	exit 1
-    fi
+	curl -sL https://raw.githubusercontent.com/openfido/cli/main/install.sh | bash
+fi
+
+if [ ! -x /usr/local/bin/openfido ]; then
+    echo "ERROR [openfido]: CLI is not installed" > /dev/stderr
+	exit 1
 else
     /usr/local/bin/openfido $*
 fi
