Update gridlabd-template

diff --git a/gldcore/scripts/gridlabd-template b/gldcore/scripts/gridlabd-template
--- a/gldcore/scripts/gridlabd-template
+++ b/gldcore/scripts/gridlabd-template
@@ -110,9 +110,9 @@ function fetch_index()
 		mkdir -p "$CACHEDIR" || error 1 "unable to create $CACHEDIR"
 	fi
 	if [ ! -f "$INDEX" ]; then
-		echo -n "Downloading ${GITBRANCH} index of $ORGANIZATION template archive from ${GITPROJ} (curl -sL $GITFILE/$ORGANIZATION/.index)... "
+		# echo -n "Downloading ${GITBRANCH} index of $ORGANIZATION template archive from ${GITPROJ} (curl -sL $GITFILE/$ORGANIZATION/.index)... "
 		curl -sL "$GITFILE/$ORGANIZATION/.index" >"$INDEX"
-		echo $(wc -l "$INDEX" | sed -e 's/ \+/ /g;s/^ //' | cut -f1 -d' ') "template files found"
+		# echo $(wc -l "$INDEX" | sed -e 's/ \+/ /g;s/^ //' | cut -f1 -d' ') "template files found"
 	fi
 	if [ ! -f "$INDEX" ]; then
 		error 1 "unable to fetch index"
@@ -220,13 +220,8 @@ function get()
 {
 	fetch_index
 	for f in $(export FORMAT=default; index $1); do
-		if [ ! -f "$DATADIR/$f" ]; then
-			echo -n "Downloading $GITFILE/$ORGANIZATION/$f.zip... "
-			(curl -sL "$GITFILE/$ORGANIZATION/$f.zip" > "/tmp/$$" && unzip -q -n -d "$DATADIR/$f" "/tmp/$$" && echo "done") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
-		else
-			echo -n "Refreshing $GITFILE/$ORGANIZATION/$f.zip... "
-			(curl -sL "$GITFILE/$ORGANIZATION/$f.zip" -z "$DATADIR/$f.zip" > "/tmp/$$" && unzip -q -u -o -d "$DATADIR/$f" "/tmp/$$" && echo "done") || (rm -f "/tmp/$$"; error 1 "unable to refresh $f")
-		fi
+		# echo -n "Downloading $GITFILE/$ORGANIZATION/$f.zip... "
+		(curl -sL "$GITFILE/$ORGANIZATION/$f.zip" > "/tmp/$$" && unzip -q -o -d "$DATADIR/$f" "/tmp/$$") || (rm -f "/tmp/$$"; error 1 "unable to download $f")
 	done
 }
 
