Update gridlabd-template

diff --git a/subcommands/gridlabd-template b/subcommands/gridlabd-template
--- a/subcommands/gridlabd-template
+++ b/subcommands/gridlabd-template
@@ -10,6 +10,7 @@ fi
 
 # configurable parameters
 GITHUB="https://github.com"
+GITAPI="https://api.github.com"
 GITHUBUSERCONTENT="https://raw.githubusercontent.com"
 if [ "${ORGANIZATION}" == "" ]; then
     export ORGANIZATION="US/CA/SLAC"
@@ -113,11 +114,12 @@ function config()
         fi
     elif [ "$1" == "reset" ]; then
         debug "resetting config"        
-        rm -f $CONFIGFILE $INDEX || error 1 "unable to reset $CONFIGFILE"
+        rm -rf "$CONFIGFILE" || error 1 "unable to delete '$CONFIGFILE'"
+        rm -rf "${INDEX}" || error 1 "unable to delete template '${INDEX}'"
     elif [ "$1" == "set" -a $# == 3 ]; then
         debug "updating config: $2 = '$3'"
-        echo "$2=\"$3\"" >> $CONFIGFILE
-        rm -f ${INDEX}
+        echo "$2=\"$3\"" >> "$CONFIGFILE"
+        rm -rf "${INDEX}" || error 1 "unable to delete template '${INDEX}'"
     elif [ "$1" == "get" -a $# == 2 ]; then
         if [ ! -r $CONFIGFILE ]; then
             value=$(config show | grep $2)
@@ -486,7 +488,7 @@ done
 CACHEDIR="$DATADIR/.gridlabd-template"
 GITPROJ="$GITHUB/$GITUSER/$GITREPO"
 GITFILE="$GITHUBUSERCONTENT/$GITUSER/$GITREPO/$GITBRANCH"
-COMMIT_ID=$(git ls-remote "$GITPROJ" | grep "$GITBRANCH" | head -n 1 | cut -f1)
+COMMIT_ID=$(curl -sL "$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH" | gridlabd json-get commit sha || error 1 "unable to find '$GITAPI/repos/$GITUSER/$GITREPO/branches/$GITBRANCH'")
 INDEX=$CACHEDIR/$COMMIT_ID
 
 # process command
