Update gridlabd-weather

diff --git a/gldcore/gridlabd-weather b/gldcore/gridlabd-weather
--- a/gldcore/gridlabd-weather
+++ b/gldcore/gridlabd-weather
@@ -32,7 +32,7 @@ function config()
 		echo "GITBRANCH=\"$GITBRANCH\""
 		echo "CACHEDIR=\"$CACHEDIR\""
 	elif [ "$1" == "reset" ]; then
-		rm -f $CONFIGFILE
+		rm -f $CONFIGFILE || (echo "ERROR: unable to reset $CONFIGFILE"; exit 1)
 	else
 		echo "'%s' is an invalid config option"
 		exit 1
@@ -49,12 +49,15 @@ INDEX=$CACHEDIR/$COMMIT_ID
 
 function fetch_index()
 {
+	if [ ! -d $DATADIR ]; then
+		mkdir -p $DATADIR || (echo "ERROR: unable to create $DATADIR"; exit 1)
+	fi
 	if [ ! -d $CACHEDIR ]; then
-		mkdir -p $CACHEDIR || ( echo "ERROR: unable to create cache directory"; exit 1)
+		mkdir -p $CACHEDIR || ( echo "ERROR: unable to create $CACHEDIR"; exit 1)
 	fi
 	if [ ! -f $INDEX ]; then
 		echo -n "Downloading ${GITBRANCH} index of $COUNTRY weather archive from ${GITPROJ}... "
-		svn $SVNLSOPTIONS ls $GITPROJ/branches/$GITBRANCH/$COUNTRY | grep '.tmy3$' > $INDEX || rm $INDEX
+		svn $SVNLSOPTIONS ls $GITPROJ/branches/$GITBRANCH/$COUNTRY | grep '.tmy3$' > $INDEX || rm -f $INDEX
 		echo $(wc -l $INDEX | sed -e 's/ \+/ /g;s/^ //' | cut -f1 -d' ') "weather files found"
 	fi
 	if [ ! -f $INDEX ]; then
@@ -86,7 +89,11 @@ function help()
 
 function clean()
 {
-	rm -rf $CACHEDIR || echo "ERROR: unable to delete $CACHEDIR"
+	rm -rf $CACHEDIR 
+	if [ -d $CACHEDIR ]; then
+		echo "ERROR: unable to delete $CACHEDIR"
+		exit 1
+	fi
 	fetch_index
 }
 
@@ -117,14 +124,10 @@ function get()
 	for f in $(index $1); do
 		if [ ! -f $DATADIR/$f ]; then
 			echo -n "Downloading $f... "
-			(curl -s $GITFILE/$COUNTRY/$f > $DATADIR/$f && echo "done") || rm $DATADIR/$f
+			(curl -s $GITFILE/$COUNTRY/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to download $f"; rm -f /tmp/$$; exit 1)
 		else
 			echo -n "Refreshing $f... "
-			(curl -s $GITFILE/$COUNTRY/$f -z $DATADIR/$f > $DATADIR/$f && echo "done") || rm $DATADIR/$f
-		fi
-		if [ ! -f $DATADIR/$f ]; then
-			echo "ERROR: unable to download $f"
-			exit 1
+			(curl -s $GITFILE/$COUNTRY/$f -z $DATADIR/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to refresh $f"; rm -f /tmp/$$; exit 1)
 		fi
 	done
 }
@@ -152,7 +155,7 @@ function delete()
 	LIST=$(index $1)
 	for f in $(index $1); do
 		if [ -f $DATADIR/$f ]; then
-			rm $DATADIR/$f || ( echo "ERROR: unable to delete %f"; exit 1)
+			rm -f $DATADIR/$f || ( echo "ERROR: unable to delete %f"; exit 1)
 		fi
 	done
 
