Update gridlabd-weather

diff --git a/gldcore/gridlabd-weather b/gldcore/gridlabd-weather
--- a/gldcore/gridlabd-weather
+++ b/gldcore/gridlabd-weather
@@ -35,7 +35,7 @@ function config()
 		echo "DATADIR=\"$DATADIR\""
 		echo "SVNLSOPTIONS=\"$SVNLSOPTIONS\""
 	elif [ "$1" == "reset" ]; then
-		rm -f $CONFIGFILE || (echo "ERROR: unable to reset $CONFIGFILE"; exit 1)
+		rm -f $CONFIGFILE || (echo "ERROR: unable to reset $CONFIGFILE" > /dev/stderr; exit 1)
 	elif [ "$1" == "set" -a $# == 3 ]; then
 		echo "$2=\"$3\"" >> $CONFIGFILE
 	elif [ "$1" == "get" -a $# == 2 ]; then
@@ -64,10 +64,10 @@ INDEX=$CACHEDIR/$COMMIT_ID
 function fetch_index()
 {
 	if [ ! -d $DATADIR ]; then
-		mkdir -p $DATADIR || (echo "ERROR: unable to create $DATADIR"; exit 1)
+		mkdir -p $DATADIR || (echo "ERROR: unable to create $DATADIR" > /dev/stderr; exit 1)
 	fi
 	if [ ! -d $CACHEDIR ]; then
-		mkdir -p $CACHEDIR || ( echo "ERROR: unable to create $CACHEDIR"; exit 1)
+		mkdir -p $CACHEDIR || ( echo "ERROR: unable to create $CACHEDIR" > /dev/stderr; exit 1)
 	fi
 	if [ ! -f $INDEX ]; then
 		echo -n "Downloading ${GITBRANCH} index of $COUNTRY weather archive from ${GITPROJ}... "
@@ -140,10 +140,10 @@ function get()
 	for f in $(index $1); do
 		if [ ! -f $DATADIR/$f ]; then
 			echo -n "Downloading $f... "
-			(curl -s $GITFILE/$COUNTRY/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to download $f"; rm -f /tmp/$$; exit 1)
+			(curl -s $GITFILE/$COUNTRY/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to download $f" > /dev/stderr; rm -f /tmp/$$; exit 1)
 		else
 			echo -n "Refreshing $f... "
-			(curl -s $GITFILE/$COUNTRY/$f -z $DATADIR/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to refresh $f"; rm -f /tmp/$$; exit 1)
+			(curl -s $GITFILE/$COUNTRY/$f -z $DATADIR/$f > /tmp/$$ && mv /tmp/$$ $DATADIR/$f && echo "done") || (echo "ERROR: unable to refresh $f" > /dev/stderr; rm -f /tmp/$$; exit 1)
 		fi
 	done
 }
@@ -169,7 +169,7 @@ function delete()
 	fetch_index
 	for f in $(index $1); do
 		if [ -f $DATADIR/$f ]; then
-			rm -f $DATADIR/$f || ( echo "ERROR: unable to delete %f"; exit 1)
+			rm -f $DATADIR/$f || ( echo "ERROR: unable to delete %f" > /dev/stderr; exit 1)
 		fi
 	done
 
